#!/bin/bash

name='GLB 2 (Lucy Angel)'
uri='glb2'
desc='Loading a Stanford's Lucy model with some depth of field.'
author='absulit'
authlink='http://absulit.com'
fitWindow=true
enabled=true
tax='showcase glb mesh threed image effects math rand animation'
