#!/bin/bash

name='Lava Lamp'
uri='lavalamp1'
desc='Raymarched spheres with random colors.<br>Made for <a rel="noopener" target="_blank" href="https://genuary.art/">Genuary</a> 12 - 2024'
author='absulit'
authlink='http://absulit.com'
fitWindow=true
enabled=true
tax='showcase raymarching math random'
