#!/bin/bash

name='Droste Effect 1'
uri='droste_effect_1'
desc='Raymarched scene with Droste Effect.<br>Based on <a rel="noopener" target="_blank" href="http://roy.red/posts/droste/">http://roy.red/posts/droste/</a>'
author='absulit'
authlink='http://absulit.com'
fitWindow=true
enabled=true
tax='showcase raymarching sdf animation math image color'
