#!/bin/bash

name='GLB 5 (Vertex Colors)'
uri='glb5'
desc='Loading a GLB file with vertex colors.'
author='absulit'
authlink='http://absulit.com'
fitWindow=true
enabled=true
tax='showcase glb mesh threed math'
