#!/bin/bash

name='GLB 4 (Animation)'
uri='glb4'
desc='Loading a GLB file with animation.'
author='absulit'
authlink='http://absulit.com'
fitWindow=true
enabled=true
tax='showcase glb mesh threed animation math'
