#!/bin/bash

name='Particles 3'
uri='particles3'
desc='Compute shader generated instanced particles.'
author='absulit'
authlink='http://absulit.com'
fitWindow=true
enabled=true
tax='showcase compute math random noise2d color sdf mesh'
