# .github/workflows/npm_publish.yml

name: Publish to npmjs.com

on:
  release:
    types: [published]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      # allow the release step to comment on
      # issues, pull requests, and write to the repo
      contents: write
      issues: write
      pull-requests: write
      # Required for OIDC to let NPM registry know
      # that this workflow is trusted
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          registry-url: https://registry.npmjs.org/

      - name: Upgrade npm
        run: npm install -g npm@latest # Ensure you have npm v11.5+

      - run: npm --version

      # nothing to install
      - name: Install dependencies
        run: npm ci
        # run: npm install

      # - name: List files
      #   run: ls -R

      - name: Publish to npm
        # remove --tag alpha on final release
        run: npm publish --provenance --access public --tag alpha
        working-directory: .
