# .github/workflows/npm_publish.yml

name: Publish to npmjs.com

on:
  release:
    types: [published]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

permissions:
  id-token: write  # Required for OIDC
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          registry-url: https://registry.npmjs.org/

      - name: Upgrade npm
        run: npm install -g npm@latest # Ensure you have npm v11.5+

      - run: npm --version

      # nothing to install
      - name: Install dependencies
        run: npm ci
        # run: npm install

      # - name: List files
      #   run: ls -R

      - name: Publish to npm
        # remove --tag alpha on final release
        run: npm publish --provenance --access public --tag alpha
        working-directory: .
